# This file was generated by GoReleaser. DO NOT EDIT.
cask "openkanban" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "fa6e9842387f792371a6458bc366ed1005a897320f40bba9451d1961e8b323e3"
      url "https://github.com/divineblu/openkanban/releases/download/v#{version}/openkanban_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/divineblu/openkanban"
    end
    on_arm do
      sha256 "f67323463dd32537e52d4b16f8aa253ea1c8fc51a7232f9fbe59abb46d60eccf"
      url "https://github.com/divineblu/openkanban/releases/download/v#{version}/openkanban_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/divineblu/openkanban"
    end
  end

  on_linux do
    on_intel do
      sha256 "74909f1f2af55acf5f2e3c49033d991d24800cf79cc5595d349adeff2aa0f8d6"
      url "https://github.com/divineblu/openkanban/releases/download/v#{version}/openkanban_#{version}_linux_amd64.tar.gz",
        verified: "github.com/divineblu/openkanban"
    end
    on_arm do
      sha256 "f6404e42289d02d8a2870fd14083063d9c35c482f9356c810500acdb073fefea"
      url "https://github.com/divineblu/openkanban/releases/download/v#{version}/openkanban_#{version}_linux_arm64.tar.gz",
        verified: "github.com/divineblu/openkanban"
    end
  end

  name "openkanban"
  desc "TUI kanban board for orchestrating AI coding agents"
  homepage "https://github.com/divineblu/openkanban"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openkanban"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/openkanban"]
    end
  end

  # No zap stanza required

end
