# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Openkanban < Formula
  desc "TUI kanban board for orchestrating AI coding agents"
  homepage "https://github.com/divineblu/openkanban"
  version "0.0.5"
  license "AGPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/divineblu/openkanban/releases/download/v0.0.5/openkanban_0.0.5_darwin_amd64.tar.gz"
      sha256 "84958a2b401c8eb0d8e05cafb2f59f8415b69691c5c79a42169ed47f53a8c2ee"

      define_method(:install) do
        bin.install "openkanban"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/divineblu/openkanban/releases/download/v0.0.5/openkanban_0.0.5_darwin_arm64.tar.gz"
      sha256 "0b1b5d7a392aebb223d9e17cf6b0385c991265d73c721c5ee93bd9d4b3259874"

      define_method(:install) do
        bin.install "openkanban"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/divineblu/openkanban/releases/download/v0.0.5/openkanban_0.0.5_linux_amd64.tar.gz"
      sha256 "680610b464301893f75b1d6bcc46cf83bdb3c7090ad8765ffcb46f7194ba52a5"
      define_method(:install) do
        bin.install "openkanban"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/divineblu/openkanban/releases/download/v0.0.5/openkanban_0.0.5_linux_arm64.tar.gz"
      sha256 "f218fd464001728e6b57a6230bc5059f5b319b57135f31c7236530d311e36711"
      define_method(:install) do
        bin.install "openkanban"
      end
    end
  end

  test do
    system "#{bin}/openkanban", "version"
  end
end
