# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Openkanban < Formula
  desc "TUI kanban board for orchestrating AI coding agents"
  homepage "https://github.com/divineblu/openkanban"
  version "0.0.2"
  license "AGPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/divineblu/openkanban/releases/download/v0.0.2/openkanban_0.0.2_darwin_amd64.tar.gz"
      sha256 "3ca442dc49b51a8e987f0435304b976c61947f707abb7ebf606bf18f76416ebc"

      define_method(:install) do
        bin.install "openkanban"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/divineblu/openkanban/releases/download/v0.0.2/openkanban_0.0.2_darwin_arm64.tar.gz"
      sha256 "09fe582029c175e1df900c5c06790d6ebddaf3d60defdf9034331f84c0e46b20"

      define_method(:install) do
        bin.install "openkanban"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/divineblu/openkanban/releases/download/v0.0.2/openkanban_0.0.2_linux_amd64.tar.gz"
      sha256 "76a6f513a04e92af6333c37c7a95c3c99597cb3d260d689e932d69a7158ff4c7"
      define_method(:install) do
        bin.install "openkanban"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/divineblu/openkanban/releases/download/v0.0.2/openkanban_0.0.2_linux_arm64.tar.gz"
      sha256 "4eecf946546933ffcebc511126d964a3a95b23ef43274fdafaaab4aa9b3d83a6"
      define_method(:install) do
        bin.install "openkanban"
      end
    end
  end

  test do
    system "#{bin}/openkanban", "version"
  end
end
