# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Openkanban < Formula
  desc "TUI kanban board for orchestrating AI coding agents"
  homepage "https://github.com/divineblu/openkanban"
  version "0.0.4"
  license "AGPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/divineblu/openkanban/releases/download/v0.0.4/openkanban_0.0.4_darwin_amd64.tar.gz"
      sha256 "be0048d29b8b92d8e559ecb4c113552616d06311f1b24be65d76ac3466eb0749"

      define_method(:install) do
        bin.install "openkanban"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/divineblu/openkanban/releases/download/v0.0.4/openkanban_0.0.4_darwin_arm64.tar.gz"
      sha256 "f0a608d92f406590ada4da0ebc9dd7c8a0c61fb097171f27d1bbfeffc80979aa"

      define_method(:install) do
        bin.install "openkanban"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/divineblu/openkanban/releases/download/v0.0.4/openkanban_0.0.4_linux_amd64.tar.gz"
      sha256 "a264b6d667334a63d06068dbad4cdf82477c79c973a259f3477d365f5b6be357"
      define_method(:install) do
        bin.install "openkanban"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/divineblu/openkanban/releases/download/v0.0.4/openkanban_0.0.4_linux_arm64.tar.gz"
      sha256 "247cd7f90df88ff25ddd72c6d6b43d80997748d6e29dda3b960a0c4a32f840e1"
      define_method(:install) do
        bin.install "openkanban"
      end
    end
  end

  test do
    system "#{bin}/openkanban", "version"
  end
end
